spring:
  application:
    name: eureka-server
  profiles:
    active: local

server:
  port: 8761

logging:
  level:
    root: info

eureka:
  instance:
    prefer-ip-address: true

management:
  endpoints.web.exposure.include: "*"
  endpoint.health.show-details: ALWAYS